### ISSUE TITLE
How to get STREAMLABS_TOKEN?

### ISSUE THREAD

**Issue by SantiMA10** [streamdevs/webhook#23]
We have to update the documentation explaining how to get the `STREAMLABS_TOKEN`.

Since Streamlabs doesn't provide an easy way to get it... maybe we can add a new endpoint to handle the Authorization process and returns the `access_token`. What do you think? @orestes

**Comment by SantiMA10** [comment]
Twitch has something similar to get tokens for bots: https://twitchapps.com/tmi/

**Comment by orestes** [comment]
We can hijack this link in the meanwhile https://tinyurl.com/ChatbotStreamlabs

**Comment by orestes** [comment]
Scopes reference: https://dev.streamlabs.com/docs/scopes

**Comment by SantiMA10** [comment]
https://github.com/streamdevs/streamlabs-token

I just build a website to get the token, should we have a live version to allow everybody to get their tokens?
