### ISSUE TITLE
Skip StreamLabs/Twitch

### ISSUE THREAD

**Issue by SantiMA10** [streamdevs/webhook#51]
Should we add a new environment variable to skip the `StreamLabs` and/or `Twitch` integrations? 
Something like: `TWITCH_ENABLE` and `STEAMLABS_ENABLE`?

**Comment by orestes** [comment]
Sounds good to me!

**Comment by SantiMA10** [comment]
Now we can achieve the same behavior by not configuring Twitch or StreamLabs, can we consider the issue close?
