### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by orestes** [streamdevs/webhook#8]
We need a logo on the Heroku [app manifest](https://github.com/streamdevs/webhook/blob/master/app.json). We're currently pointing to an inexistent file.

This makes it look ugly when using the "deploy with Heroku button"

![image](https://user-images.githubusercontent.com/618107/79023264-1feede80-7b80-11ea-87e3-0cdd6ed7b02e.png)

**Comment by SantiMA10** [comment]
Still not working
